from __future__ import annotations

import sys
from enum import Enum, auto
from typing import Callable, List, Union

from medmodels.medrecord.types import Group, MedRecordAttribute, MedRecordValue

if sys.version_info >= (3, 10):
    from typing import TypeAlias
else:
    from typing_extensions import TypeAlias

NodeQuery: TypeAlias = Callable[[NodeOperand], None]
EdgeQuery: TypeAlias = Callable[[EdgeOperand], None]

ValueOperand: TypeAlias = Union[NodeValueOperand, EdgeValueOperand, MedRecordValue]
ValuesOperand: TypeAlias = Union[
    NodeValuesOperand, EdgeValuesOperand, List[MedRecordValue]
]
ComparisonOperand: TypeAlias = Union[ValueOperand, ValuesOperand]

class EdgeDirection(Enum):
    INCOMING = auto()
    OUTGOING = auto()
    BOTH = auto()

class NodeOperand:
    def attribute(self, attribute: MedRecordAttribute) -> NodeValuesOperand: ...
    def index(self) -> NodeValuesOperand: ...
    def in_group(self, group: Union[Group, List[Group]]) -> None: ...
    def has_attribute(
        self, attribute: Union[MedRecordAttribute, List[MedRecordAttribute]]
    ) -> None: ...
    def incoming_edges(self) -> EdgeOperand: ...
    def outgoing_edges(self) -> EdgeOperand: ...
    def neighbors(
        self, edge_direction: EdgeDirection = EdgeDirection.OUTGOING
    ) -> NodeOperand: ...
    def either_or(self, either: NodeQuery, or_: NodeQuery) -> None: ...

class EdgeOperand:
    def attribute(self, attribute: MedRecordAttribute) -> EdgeValuesOperand: ...
    def index(self) -> EdgeValuesOperand: ...
    def in_group(self, group: Union[Group, List[Group]]) -> None: ...
    def has_attribute(
        self, attribute: Union[MedRecordAttribute, List[MedRecordAttribute]]
    ) -> None: ...
    def source_node(self) -> NodeOperand: ...
    def target_node(self) -> NodeOperand: ...
    def either_or(self, either: EdgeQuery, or_: EdgeQuery) -> None: ...

class NodeValuesOperand:
    def max(self) -> NodeValueOperand: ...
    def min(self) -> NodeValueOperand: ...
    def mean(self) -> NodeValueOperand: ...
    def all(self) -> NodeValueOperand: ...
    def any(self) -> NodeValueOperand: ...
    def greater_than(self, value: ComparisonOperand) -> None: ...
    def greater_than_or_equal(self, value: ComparisonOperand) -> None: ...
    def less_than(self, value: ComparisonOperand) -> None: ...
    def less_than_or_equal(self, value: ComparisonOperand) -> None: ...
    def equals(self, value: ComparisonOperand) -> None: ...
    def not_equals(self, value: ComparisonOperand) -> None: ...
    def is_in(self, values: ValuesOperand) -> None: ...
    def is_not_in(self, values: ValuesOperand) -> None: ...
    def starts_with(self, value: ComparisonOperand) -> None: ...
    def ends_with(self, value: ComparisonOperand) -> None: ...
    def contains(self, value: ComparisonOperand) -> None: ...
    def add(self, value: ComparisonOperand) -> NodeValuesOperand: ...
    def subtract(self, value: ComparisonOperand) -> NodeValuesOperand: ...
    def multiply(self, value: ComparisonOperand) -> NodeValuesOperand: ...
    def divide(self, value: ComparisonOperand) -> NodeValuesOperand: ...
    def modulo(self, value: ComparisonOperand) -> NodeValuesOperand: ...
    def power(self, value: ComparisonOperand) -> NodeValuesOperand: ...
    def round(self) -> NodeValuesOperand: ...
    def ceil(self) -> NodeValuesOperand: ...
    def floor(self) -> NodeValuesOperand: ...
    def absolute(self) -> NodeValuesOperand: ...
    def sqrt(self) -> NodeValuesOperand: ...
    def trim(self) -> NodeValuesOperand: ...
    def trim_start(self) -> NodeValuesOperand: ...
    def trim_end(self) -> NodeValuesOperand: ...
    def lowercase(self) -> NodeValuesOperand: ...
    def uppercase(self) -> NodeValuesOperand: ...
    def slice(self, start: int, end: int) -> NodeValuesOperand: ...

class EdgeValuesOperand:
    def max(self) -> EdgeValueOperand: ...
    def min(self) -> EdgeValueOperand: ...
    def mean(self) -> EdgeValueOperand: ...
    def all(self) -> EdgeValueOperand: ...
    def any(self) -> EdgeValueOperand: ...
    def greater_than(self, value: ComparisonOperand) -> None: ...
    def greater_than_or_equal(self, value: ComparisonOperand) -> None: ...
    def less_than(self, value: ComparisonOperand) -> None: ...
    def less_than_or_equal(self, value: ComparisonOperand) -> None: ...
    def equals(self, value: ComparisonOperand) -> None: ...
    def not_equals(self, value: ComparisonOperand) -> None: ...
    def is_in(self, values: ValuesOperand) -> None: ...
    def is_not_in(self, values: ValuesOperand) -> None: ...
    def starts_with(self, value: ComparisonOperand) -> None: ...
    def ends_with(self, value: ComparisonOperand) -> None: ...
    def contains(self, value: ComparisonOperand) -> None: ...
    def add(self, value: ComparisonOperand) -> EdgeValuesOperand: ...
    def subtract(self, value: ComparisonOperand) -> EdgeValuesOperand: ...
    def multiply(self, value: ComparisonOperand) -> EdgeValuesOperand: ...
    def divide(self, value: ComparisonOperand) -> EdgeValuesOperand: ...
    def modulo(self, value: ComparisonOperand) -> EdgeValuesOperand: ...
    def power(self, value: ComparisonOperand) -> EdgeValuesOperand: ...
    def round(self) -> EdgeValuesOperand: ...
    def ceil(self) -> EdgeValuesOperand: ...
    def floor(self) -> EdgeValuesOperand: ...
    def absolute(self) -> EdgeValuesOperand: ...
    def sqrt(self) -> EdgeValuesOperand: ...
    def trim(self) -> EdgeValuesOperand: ...
    def trim_start(self) -> EdgeValuesOperand: ...
    def trim_end(self) -> EdgeValuesOperand: ...
    def lowercase(self) -> EdgeValuesOperand: ...
    def uppercase(self) -> EdgeValuesOperand: ...
    def slice(self, start: int, end: int) -> EdgeValuesOperand: ...

class NodeValueOperand:
    def greater_than(self, value: ComparisonOperand) -> None: ...
    def greater_than_or_equal(self, value: ComparisonOperand) -> None: ...
    def less_than(self, value: ComparisonOperand) -> None: ...
    def less_than_or_equal(self, value: ComparisonOperand) -> None: ...
    def equals(self, value: ComparisonOperand) -> None: ...
    def not_equals(self, value: ComparisonOperand) -> None: ...
    def is_in(self, values: ValuesOperand) -> None: ...
    def is_not_in(self, values: ValuesOperand) -> None: ...
    def starts_with(self, value: ComparisonOperand) -> None: ...
    def ends_with(self, value: ComparisonOperand) -> None: ...
    def contains(self, value: ComparisonOperand) -> None: ...
    def add(self, value: ComparisonOperand) -> NodeValueOperand: ...
    def subtract(self, value: ComparisonOperand) -> NodeValueOperand: ...
    def multiply(self, value: ComparisonOperand) -> NodeValueOperand: ...
    def divide(self, value: ComparisonOperand) -> NodeValueOperand: ...
    def modulo(self, value: ComparisonOperand) -> NodeValueOperand: ...
    def power(self, value: ComparisonOperand) -> NodeValueOperand: ...
    def round(self) -> NodeValueOperand: ...
    def ceil(self) -> NodeValueOperand: ...
    def floor(self) -> NodeValueOperand: ...
    def absolute(self) -> NodeValueOperand: ...
    def sqrt(self) -> NodeValueOperand: ...
    def trim(self) -> NodeValueOperand: ...
    def trim_start(self) -> NodeValueOperand: ...
    def trim_end(self) -> NodeValueOperand: ...
    def lowercase(self) -> NodeValueOperand: ...
    def uppercase(self) -> NodeValueOperand: ...
    def slice(self, start: int, end: int) -> NodeValueOperand: ...

class EdgeValueOperand:
    def greater_than(self, value: ComparisonOperand) -> None: ...
    def greater_than_or_equal(self, value: ComparisonOperand) -> None: ...
    def less_than(self, value: ComparisonOperand) -> None: ...
    def less_than_or_equal(self, value: ComparisonOperand) -> None: ...
    def equals(self, value: ComparisonOperand) -> None: ...
    def not_equals(self, value: ComparisonOperand) -> None: ...
    def is_in(self, values: ValuesOperand) -> None: ...
    def is_not_in(self, values: ValuesOperand) -> None: ...
    def starts_with(self, value: ComparisonOperand) -> None: ...
    def ends_with(self, value: ComparisonOperand) -> None: ...
    def contains(self, value: ComparisonOperand) -> None: ...
    def add(self, value: ComparisonOperand) -> EdgeValueOperand: ...
    def subtract(self, value: ComparisonOperand) -> EdgeValueOperand: ...
    def multiply(self, value: ComparisonOperand) -> EdgeValueOperand: ...
    def divide(self, value: ComparisonOperand) -> EdgeValueOperand: ...
    def modulo(self, value: ComparisonOperand) -> EdgeValueOperand: ...
    def power(self, value: ComparisonOperand) -> EdgeValueOperand: ...
    def round(self) -> EdgeValueOperand: ...
    def ceil(self) -> EdgeValueOperand: ...
    def floor(self) -> EdgeValueOperand: ...
    def absolute(self) -> EdgeValueOperand: ...
    def sqrt(self) -> EdgeValueOperand: ...
    def trim(self) -> EdgeValueOperand: ...
    def trim_start(self) -> EdgeValueOperand: ...
    def trim_end(self) -> EdgeValueOperand: ...
    def lowercase(self) -> EdgeValueOperand: ...
    def uppercase(self) -> EdgeValueOperand: ...
    def slice(self, start: int, end: int) -> EdgeValueOperand: ...
