from __future__ import annotations

import sys
from enum import Enum, auto
from typing import Callable, List, Union

from medmodels.medrecord.types import (
    EdgeIndex,
    Group,
    MedRecordAttribute,
    MedRecordValue,
)

if sys.version_info >= (3, 10):
    from typing import TypeAlias
else:
    from typing_extensions import TypeAlias

NodeQuery: TypeAlias = Callable[[NodeOperand], None]
EdgeQuery: TypeAlias = Callable[[EdgeOperand], None]

ValueComparisonOperand: TypeAlias = Union[
    SingleValueOperand, MedRecordValue, MultipleValuesOperand, List[MedRecordValue]
]
ValueArithmeticOperand: TypeAlias = Union[SingleValueOperand, MedRecordValue]
AttributeComparisonOperand: TypeAlias = Union[
    SingleAttributeOperand,
    MedRecordAttribute,
    MultipleAttributesOperand,
    List[MedRecordAttribute],
]
AttributeArithmeticOperand: TypeAlias = Union[
    SingleAttributeOperand, MedRecordAttribute
]
EdgeIndexComparisonOperand: TypeAlias = Union[
    EdgeIndexOperand,
    EdgeIndex,
    EdgeIndicesOperand,
    List[EdgeIndex],
]
EdgeIndexArithmeticOperand: TypeAlias = Union[EdgeIndexOperand, EdgeIndex]

class EdgeDirection(Enum):
    INCOMING = auto()
    OUTGOING = auto()
    BOTH = auto()

class NodeOperand:
    def attribute(self, attribute: MedRecordAttribute) -> MultipleValuesOperand: ...
    def attributes(self) -> MultipleAttributesOperand: ...
    def index(self) -> NodeIndexOperand: ...
    def in_group(self, group: Union[Group, List[Group]]) -> None: ...
    def has_attribute(
        self, attribute: Union[MedRecordAttribute, List[MedRecordAttribute]]
    ) -> None: ...
    def incoming_edges(self) -> EdgeOperand: ...
    def outgoing_edges(self) -> EdgeOperand: ...
    def neighbors(
        self, edge_direction: EdgeDirection = EdgeDirection.OUTGOING
    ) -> NodeOperand: ...
    def either_or(self, either: NodeQuery, or_: NodeQuery) -> None: ...

class EdgeOperand:
    def attribute(self, attribute: MedRecordAttribute) -> MultipleValuesOperand: ...
    def attributes(self) -> MultipleAttributesOperand: ...
    def index(self) -> EdgeIndexOperand: ...
    def in_group(self, group: Union[Group, List[Group]]) -> None: ...
    def has_attribute(
        self, attribute: Union[MedRecordAttribute, List[MedRecordAttribute]]
    ) -> None: ...
    def source_node(self) -> NodeOperand: ...
    def target_node(self) -> NodeOperand: ...
    def either_or(self, either: EdgeQuery, or_: EdgeQuery) -> None: ...

class MultipleValuesOperand:
    def max(self) -> SingleValueOperand: ...
    def min(self) -> SingleValueOperand: ...
    def mean(self) -> SingleValueOperand: ...
    def any(self, query: Callable[[SingleValueOperand], None]) -> None: ...
    def is_string(self) -> None: ...
    def is_int(self) -> None: ...
    def is_float(self) -> None: ...
    def is_bool(self) -> None: ...
    def is_datetime(self) -> None: ...
    def greater_than(self, value: ValueComparisonOperand) -> None: ...
    def greater_than_or_equal(self, value: ValueComparisonOperand) -> None: ...
    def less_than(self, value: ValueComparisonOperand) -> None: ...
    def less_than_or_equal(self, value: ValueComparisonOperand) -> None: ...
    def equal_to(self, value: ValueComparisonOperand) -> None: ...
    def not_equal_to(self, value: ValueComparisonOperand) -> None: ...
    def is_in(self, values: ValueComparisonOperand) -> None: ...
    def is_not_in(self, values: ValueComparisonOperand) -> None: ...
    def starts_with(self, value: ValueComparisonOperand) -> None: ...
    def ends_with(self, value: ValueComparisonOperand) -> None: ...
    def contains(self, value: ValueComparisonOperand) -> None: ...
    def add(self, value: ValueArithmeticOperand) -> MultipleValuesOperand: ...
    def subtract(self, value: ValueArithmeticOperand) -> MultipleValuesOperand: ...
    def multiply(self, value: ValueArithmeticOperand) -> MultipleValuesOperand: ...
    def divide(self, value: ValueArithmeticOperand) -> MultipleValuesOperand: ...
    def modulo(self, value: ValueArithmeticOperand) -> MultipleValuesOperand: ...
    def power(self, value: ValueArithmeticOperand) -> MultipleValuesOperand: ...
    def round(self) -> MultipleValuesOperand: ...
    def ceil(self) -> MultipleValuesOperand: ...
    def floor(self) -> MultipleValuesOperand: ...
    def absolute(self) -> MultipleValuesOperand: ...
    def sqrt(self) -> MultipleValuesOperand: ...
    def trim(self) -> MultipleValuesOperand: ...
    def trim_start(self) -> MultipleValuesOperand: ...
    def trim_end(self) -> MultipleValuesOperand: ...
    def lowercase(self) -> MultipleValuesOperand: ...
    def uppercase(self) -> MultipleValuesOperand: ...
    def slice(self, start: int, end: int) -> MultipleValuesOperand: ...
    def either_or(
        self, either: MultipleValuesOperand, or_: MultipleValuesOperand
    ) -> None: ...

class SingleValueOperand:
    def is_string(self) -> None: ...
    def is_int(self) -> None: ...
    def is_float(self) -> None: ...
    def is_bool(self) -> None: ...
    def is_datetime(self) -> None: ...
    def greater_than(self, value: ValueComparisonOperand) -> None: ...
    def greater_than_or_equal(self, value: ValueComparisonOperand) -> None: ...
    def less_than(self, value: ValueComparisonOperand) -> None: ...
    def less_than_or_equal(self, value: ValueComparisonOperand) -> None: ...
    def equal_to(self, value: ValueComparisonOperand) -> None: ...
    def not_equal_to(self, value: ValueComparisonOperand) -> None: ...
    def is_in(self, values: ValueComparisonOperand) -> None: ...
    def is_not_in(self, values: ValueComparisonOperand) -> None: ...
    def starts_with(self, value: ValueComparisonOperand) -> None: ...
    def ends_with(self, value: ValueComparisonOperand) -> None: ...
    def contains(self, value: ValueComparisonOperand) -> None: ...
    def add(self, value: ValueArithmeticOperand) -> SingleValueOperand: ...
    def subtract(self, value: ValueArithmeticOperand) -> SingleValueOperand: ...
    def multiply(self, value: ValueArithmeticOperand) -> SingleValueOperand: ...
    def divide(self, value: ValueArithmeticOperand) -> SingleValueOperand: ...
    def modulo(self, value: ValueArithmeticOperand) -> SingleValueOperand: ...
    def power(self, value: ValueArithmeticOperand) -> SingleValueOperand: ...
    def round(self) -> SingleValueOperand: ...
    def ceil(self) -> SingleValueOperand: ...
    def floor(self) -> SingleValueOperand: ...
    def absolute(self) -> SingleValueOperand: ...
    def sqrt(self) -> SingleValueOperand: ...
    def trim(self) -> SingleValueOperand: ...
    def trim_start(self) -> SingleValueOperand: ...
    def trim_end(self) -> SingleValueOperand: ...
    def lowercase(self) -> SingleValueOperand: ...
    def uppercase(self) -> SingleValueOperand: ...
    def slice(self, start: int, end: int) -> SingleValueOperand: ...
    def either_or(
        self, either: SingleValueOperand, or_: SingleValueOperand
    ) -> None: ...

class MultipleAttributesOperand:
    def max(self) -> SingleAttributeOperand: ...
    def min(self) -> SingleAttributeOperand: ...
    def mean(self) -> SingleAttributeOperand: ...
    def is_string(self) -> None: ...
    def is_int(self) -> None: ...
    def is_float(self) -> None: ...
    def is_bool(self) -> None: ...
    def is_datetime(self) -> None: ...
    def any(self, query: Callable[[SingleAttributeOperand], None]) -> None: ...
    def greater_than(self, value: AttributeComparisonOperand) -> None: ...
    def greater_than_or_equal(self, value: AttributeComparisonOperand) -> None: ...
    def less_than(self, value: AttributeComparisonOperand) -> None: ...
    def less_than_or_equal(self, value: AttributeComparisonOperand) -> None: ...
    def equal_to(self, value: AttributeComparisonOperand) -> None: ...
    def not_equal_to(self, value: AttributeComparisonOperand) -> None: ...
    def is_in(self, values: AttributeComparisonOperand) -> None: ...
    def is_not_in(self, values: AttributeComparisonOperand) -> None: ...
    def starts_with(self, value: AttributeComparisonOperand) -> None: ...
    def ends_with(self, value: AttributeComparisonOperand) -> None: ...
    def contains(self, value: AttributeComparisonOperand) -> None: ...
    def add(self, value: AttributeArithmeticOperand) -> MultipleAttributesOperand: ...
    def subtract(
        self, value: AttributeArithmeticOperand
    ) -> MultipleAttributesOperand: ...
    def multiply(
        self, value: AttributeArithmeticOperand
    ) -> MultipleAttributesOperand: ...
    def divide(
        self, value: AttributeArithmeticOperand
    ) -> MultipleAttributesOperand: ...
    def modulo(
        self, value: AttributeArithmeticOperand
    ) -> MultipleAttributesOperand: ...
    def power(self, value: AttributeArithmeticOperand) -> MultipleAttributesOperand: ...
    def round(self) -> MultipleAttributesOperand: ...
    def ceil(self) -> MultipleAttributesOperand: ...
    def floor(self) -> MultipleAttributesOperand: ...
    def absolute(self) -> MultipleAttributesOperand: ...
    def sqrt(self) -> MultipleAttributesOperand: ...
    def trim(self) -> MultipleAttributesOperand: ...
    def trim_start(self) -> MultipleAttributesOperand: ...
    def trim_end(self) -> MultipleAttributesOperand: ...
    def lowercase(self) -> MultipleAttributesOperand: ...
    def uppercase(self) -> MultipleAttributesOperand: ...
    def slice(self, start: int, end: int) -> MultipleAttributesOperand: ...
    def either_or(
        self, either: MultipleAttributesOperand, or_: MultipleAttributesOperand
    ) -> None: ...

class SingleAttributeOperand:
    def is_string(self) -> None: ...
    def is_int(self) -> None: ...
    def is_float(self) -> None: ...
    def is_bool(self) -> None: ...
    def is_datetime(self) -> None: ...
    def greater_than(self, value: AttributeComparisonOperand) -> None: ...
    def greater_than_or_equal(self, value: AttributeComparisonOperand) -> None: ...
    def less_than(self, value: AttributeComparisonOperand) -> None: ...
    def less_than_or_equal(self, value: AttributeComparisonOperand) -> None: ...
    def equal_to(self, value: AttributeComparisonOperand) -> None: ...
    def not_equal_to(self, value: AttributeComparisonOperand) -> None: ...
    def is_in(self, values: AttributeComparisonOperand) -> None: ...
    def is_not_in(self, values: AttributeComparisonOperand) -> None: ...
    def starts_with(self, value: AttributeComparisonOperand) -> None: ...
    def ends_with(self, value: AttributeComparisonOperand) -> None: ...
    def contains(self, value: AttributeComparisonOperand) -> None: ...
    def add(self, value: AttributeArithmeticOperand) -> SingleAttributeOperand: ...
    def subtract(self, value: AttributeArithmeticOperand) -> SingleAttributeOperand: ...
    def multiply(self, value: AttributeArithmeticOperand) -> SingleAttributeOperand: ...
    def divide(self, value: AttributeArithmeticOperand) -> SingleAttributeOperand: ...
    def modulo(self, value: AttributeArithmeticOperand) -> SingleAttributeOperand: ...
    def power(self, value: AttributeArithmeticOperand) -> SingleAttributeOperand: ...
    def round(self) -> SingleAttributeOperand: ...
    def ceil(self) -> SingleAttributeOperand: ...
    def floor(self) -> SingleAttributeOperand: ...
    def absolute(self) -> SingleAttributeOperand: ...
    def sqrt(self) -> SingleAttributeOperand: ...
    def trim(self) -> SingleAttributeOperand: ...
    def trim_start(self) -> SingleAttributeOperand: ...
    def trim_end(self) -> SingleAttributeOperand: ...
    def lowercase(self) -> SingleAttributeOperand: ...
    def uppercase(self) -> SingleAttributeOperand: ...
    def slice(self, start: int, end: int) -> SingleAttributeOperand: ...
    def either_or(
        self, either: SingleAttributeOperand, or_: SingleAttributeOperand
    ) -> None: ...

NodeIndicesOperand: TypeAlias = MultipleAttributesOperand
NodeIndexOperand: TypeAlias = SingleAttributeOperand

class EdgeIndicesOperand:
    def max(self) -> EdgeIndexOperand: ...
    def min(self) -> EdgeIndexOperand: ...
    def mean(self) -> EdgeIndexOperand: ...
    def any(self, query: Callable[[EdgeIndexOperand], None]) -> None: ...
    def is_string(self) -> None: ...
    def is_int(self) -> None: ...
    def is_float(self) -> None: ...
    def is_bool(self) -> None: ...
    def is_datetime(self) -> None: ...
    def greater_than(self, value: EdgeIndexComparisonOperand) -> None: ...
    def greater_than_or_equal(self, value: EdgeIndexComparisonOperand) -> None: ...
    def less_than(self, value: EdgeIndexComparisonOperand) -> None: ...
    def less_than_or_equal(self, value: EdgeIndexComparisonOperand) -> None: ...
    def equal_to(self, value: EdgeIndexComparisonOperand) -> None: ...
    def not_equal_to(self, value: EdgeIndexComparisonOperand) -> None: ...
    def is_in(self, values: EdgeIndexComparisonOperand) -> None: ...
    def is_not_in(self, values: EdgeIndexComparisonOperand) -> None: ...
    def starts_with(self, value: EdgeIndexComparisonOperand) -> None: ...
    def ends_with(self, value: EdgeIndexComparisonOperand) -> None: ...
    def contains(self, value: EdgeIndexComparisonOperand) -> None: ...
    def add(self, value: EdgeIndexArithmeticOperand) -> MultipleAttributesOperand: ...
    def subtract(
        self, value: EdgeIndexArithmeticOperand
    ) -> MultipleAttributesOperand: ...
    def multiply(
        self, value: EdgeIndexArithmeticOperand
    ) -> MultipleAttributesOperand: ...
    def divide(
        self, value: EdgeIndexArithmeticOperand
    ) -> MultipleAttributesOperand: ...
    def modulo(
        self, value: EdgeIndexArithmeticOperand
    ) -> MultipleAttributesOperand: ...
    def power(self, value: EdgeIndexArithmeticOperand) -> MultipleAttributesOperand: ...
    def round(self) -> MultipleAttributesOperand: ...
    def ceil(self) -> MultipleAttributesOperand: ...
    def floor(self) -> MultipleAttributesOperand: ...
    def absolute(self) -> MultipleAttributesOperand: ...
    def sqrt(self) -> MultipleAttributesOperand: ...
    def trim(self) -> MultipleAttributesOperand: ...
    def trim_start(self) -> MultipleAttributesOperand: ...
    def trim_end(self) -> MultipleAttributesOperand: ...
    def lowercase(self) -> MultipleAttributesOperand: ...
    def uppercase(self) -> MultipleAttributesOperand: ...
    def slice(self, start: int, end: int) -> MultipleAttributesOperand: ...
    def either_or(
        self, either: MultipleAttributesOperand, or_: MultipleAttributesOperand
    ) -> None: ...

class EdgeIndexOperand:
    def is_string(self) -> None: ...
    def is_int(self) -> None: ...
    def is_float(self) -> None: ...
    def is_bool(self) -> None: ...
    def is_datetime(self) -> None: ...
    def greater_than(self, value: EdgeIndexComparisonOperand) -> None: ...
    def greater_than_or_equal(self, value: EdgeIndexComparisonOperand) -> None: ...
    def less_than(self, value: EdgeIndexComparisonOperand) -> None: ...
    def less_than_or_equal(self, value: EdgeIndexComparisonOperand) -> None: ...
    def equal_to(self, value: EdgeIndexComparisonOperand) -> None: ...
    def not_equal_to(self, value: EdgeIndexComparisonOperand) -> None: ...
    def is_in(self, values: EdgeIndexComparisonOperand) -> None: ...
    def is_not_in(self, values: EdgeIndexComparisonOperand) -> None: ...
    def starts_with(self, value: EdgeIndexComparisonOperand) -> None: ...
    def ends_with(self, value: EdgeIndexComparisonOperand) -> None: ...
    def contains(self, value: EdgeIndexComparisonOperand) -> None: ...
    def add(self, value: EdgeIndexArithmeticOperand) -> SingleAttributeOperand: ...
    def subtract(self, value: EdgeIndexArithmeticOperand) -> SingleAttributeOperand: ...
    def multiply(self, value: EdgeIndexArithmeticOperand) -> SingleAttributeOperand: ...
    def divide(self, value: EdgeIndexArithmeticOperand) -> SingleAttributeOperand: ...
    def modulo(self, value: EdgeIndexArithmeticOperand) -> SingleAttributeOperand: ...
    def power(self, value: EdgeIndexArithmeticOperand) -> SingleAttributeOperand: ...
    def round(self) -> SingleAttributeOperand: ...
    def ceil(self) -> SingleAttributeOperand: ...
    def floor(self) -> SingleAttributeOperand: ...
    def absolute(self) -> SingleAttributeOperand: ...
    def sqrt(self) -> SingleAttributeOperand: ...
    def trim(self) -> SingleAttributeOperand: ...
    def trim_start(self) -> SingleAttributeOperand: ...
    def trim_end(self) -> SingleAttributeOperand: ...
    def lowercase(self) -> SingleAttributeOperand: ...
    def uppercase(self) -> SingleAttributeOperand: ...
    def slice(self, start: int, end: int) -> SingleAttributeOperand: ...
    def either_or(
        self, either: SingleAttributeOperand, or_: SingleAttributeOperand
    ) -> None: ...
