name: 🐛 Bug report
description: Report a bug to help us improve 💪
labels: [bug, needs triage]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Preliminary checks
      options:
        - label: I have checked that this issue has not already been reported.
        - label: I have checked that this issue has not been fixed in the latest version.
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior or a simple, minimal, self-contained script that can immediately reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happens when the bug occurs.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, such as the Python version, the operating system, and installed packages.
    validations:
      required: false
