"""Critic for MTGAN."""

import torch
from torch import nn


class Critic(nn.Module):
    """Critic for the MTGAN model.

    It is used to evaluate the quality of the synthetic data generated by the
    generator.
    """

    number_codes: int
    critic_hidden_dimension: int
    generator_hidden_dimension: int

    linear: nn.Sequential

    def __init__(
        self,
        number_codes: int,
        critic_hidden_dimension: int,
        generator_hidden_dimension: int,
    ) -> None: ...
    def forward(
        self, data: torch.Tensor, hiddens: torch.Tensor, number_admissions: torch.Tensor
    ) -> torch.Tensor: ...
