from typing import List, Optional, Dict
from polars import DataFrame

class PyMedRecord:
    nodes: List[str]
    edges: List[tuple[str, str]]
    groups: List[str]

    def __init__(self) -> None: ...
    @staticmethod
    def from_tuples(
        nodes: List[tuple[str, Dict]], edges: Optional[List[tuple[str, str, Dict]]]
    ) -> PyMedRecord: ...
    @staticmethod
    def from_dataframes(
        nodes_dataframe: DataFrame,
        nodes_index_column_name: str,
        edges_dataframe: DataFrame,
        edges_from_index_column_name: str,
        edges_to_index_column_name: str,
    ) -> PyMedRecord: ...
    @staticmethod
    def from_nodes_dataframe(
        nodes_dataframe: DataFrame,
        nodes_index_column_name: str,
    ) -> PyMedRecord: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def group_count(self) -> int: ...
    def node(self, *node_id: str) -> List[tuple[str, Dict]]: ...
    def edges_between(self, start_node_id: str, end_node_id: str) -> List[Dict]: ...
    def group(self, *group: str) -> List[tuple[str, Dict]]: ...
    def add_nodes(self, nodes: List[tuple[str, Dict]]) -> None: ...
    def add_nodes_dataframe(
        self, nodes_dataframe: DataFrame, index_column_name: str
    ) -> None: ...
    def add_edges(self, edges: List[tuple[str, str, Dict]]) -> None: ...
    def add_edges_dataframe(
        self,
        edges_dataframe: DataFrame,
        from_index_column_name: str,
        to_index_column_name: str,
    ) -> None: ...
    def add_group(self, group: str, node_ids_to_add: Optional[List[str]]) -> None: ...
    def remove_group(self, group: str) -> None: ...
    def remove_from_group(self, group: str, node_id: str) -> None: ...
    def add_to_group(self, group: str, node_id: str) -> None: ...
    def neighbors(self, *node_id: str) -> List[tuple[str, Dict]]: ...
