from typing import Dict, List, Tuple

from numpy.typing import ArrayLike

def test_for_normal_distribution(sample: ArrayLike) -> bool: ...
def decide_hypothesis_test(
    samples: List[ArrayLike], alpha: float
) -> Dict[str, Tuple[str, bool, float]]: ...
def two_tailed_t_test(
    samples: List[ArrayLike], alpha: float
) -> Tuple[str, bool, float]: ...
def mann_whitney_u_test(
    samples: List[ArrayLike], alpha: float
) -> Tuple[str, bool, float]: ...
def test_ANOVA(samples: List[ArrayLike], alpha: float) -> Tuple[str, bool, float]: ...
def chi_square_independece_test(
    samples: List[ArrayLike], alpha: float
) -> Tuple[str, bool, float]: ...
def measure_effect_size(samples: List[ArrayLike]) -> Tuple[str, float]: ...
def glass_delta(
    mean_control: float, mean_treatment: float, std_control: float
) -> float: ...
def cohens_d(
    mean_control: float, mean_treatment: float, std_control: float, std_treatment: float
) -> float: ...
def hedges_d(
    mean_control: float, mean_treatment: float, std_control: float, std_treatment: float
) -> float: ...
