from typing import List
from polars import DataFrame

class Medrecord:
    nodes: List[str]
    edges: List[tuple[str, str]]

    def __init__(self) -> None: ...
    def from_nodes_and_edges(
        nodes: List[tuple[str, object]], edges: List[tuple[str, str, object]]
    ) -> Medrecord: ...
    def from_dataframes(
        nodes_dataframe: DataFrame,
        edges_dataframe: DataFrame,
        node_index_column_name: str,
        node_attribute_column_names: List[str],
        edge_from_index_column_name: str,
        edge_to_index_column_name: str,
        edge_attribute_column_names: List[str],
    ) -> Medrecord: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def node(self, *node_id: str) -> List[tuple[str, object]]: ...
    def edges_between(self, start_node_id: str, end_node_id: str) -> List[object]: ...
    def add_nodes(self, nodes: List[tuple[str, object]]) -> None: ...
    def add_edges(self, edges: List[tuple[str, str, object]]) -> None: ...
